version: 2
updates:
  # Dependabot uses the npm ecosystem value for pnpm projects.
  - package-ecosystem: npm
    directory: /dev
    schedule:
      interval: weekly
    groups:
      pnpm-dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: uv
    directory: /dev
    schedule:
      interval: weekly
    groups:
      uv-dev-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
