name: "Setup"
description: "Install Foundry"

runs:
  using: "composite"
  steps:
    - name: "Install Foundry"
      uses: "foundry-rs/foundry-toolchain@c7450ba673e133f5ee30098b3b54f444d3a2ca2d"
      with:
        version: "stable"

    - name: "Show the Foundry config"
      shell: "bash"
      run: "forge --version && echo '\n' && forge config"
